apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "https://localhost:8889"     # TODO : url 환경마다 다름
  subscriptions: |
    - recipients:
      - slack-webhook
      triggers:
      - on-sync-succeeded
      - on-sync-status-unknown
      - on-sync-failed
  service.webhook.slack-webhook: |
    url: $slack-webhook-url
    headers:
      - name: Content-Type
        value: application/json
  template.app-sync-succeeded: |
    webhook:
      slack-webhook:
        method: POST
        body: |
          {
            "text": ":white_check_mark: {{.app.metadata.name}} has been successfully synced.",
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#18be52",
              "fields": [{
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              },{
                "title": "Path",
                "value": "{{.app.spec.source.path}}",
                "short": true
              },{
                "title": "Target Revision",
                "value": "{{.app.spec.source.targetRevision}}",
                "short": true
              },{
                "title": "Commit",
                "value": "{{.app.spec.source.repoURL}}/{{.app.status.sync.revision}}",
                "short": true
              },{
                "title": "Author",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
                "short": true
              },{
                "title": "Message",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
                "short": true
              }]
            }]
          }
  template.app-sync-status-unknown: |
    webhook:
      slack-webhook:
        method: POST
        body: |
          {
            "text": ":exclamation: {{.app.metadata.name}} sync status is 'Unknown'",
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#E96D76",
              "fields": [{
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              },{
                "title": "Path",
                "value": "{{.app.spec.source.path}}",
                "short": true
              },{
                "title": "Target Revision",
                "value": "{{.app.spec.source.targetRevision}}",
                "short": true
              }
              {{if .app.status.sync.revision}}
              ,
              {
                "title": "Commit",
                "value": "{{.app.spec.source.repoURL}}/{{.app.status.sync.revision}}",
                "short": true
              },{
                "title": "Author",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
                "short": true
              },{
                "title": "Message",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
                "short": true
              }
              {{end}}
              {{if .app.status.operationState.message}}
              ,
              {
                "title": "Error Message",
                "value": "{{.app.status.operationState.message}}",
                "short": true
              }
              {{end}}
              {{range $index, $c := .app.status.conditions}}
              {{if not $index}},{{end}}
              {{if $index}},{{end}}
              {
                "title": "{{$c.type}}",
                "value": "{{$c.message}}",
                "short": true
              }
              {{end}}
              ]
            }]
          }
  template.app-sync-failed: |
    webhook:
      slack-webhook:
        method: POST
        body: |
          {
            "text": ":no_entry: Failed to sync {{.app.metadata.name}}",
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#E96D76",
              "fields": [{
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              },{
                "title": "Path",
                "value": "{{.app.spec.source.path}}",
                "short": true
              },{
                "title": "Target Revision",
                "value": "{{.app.spec.source.targetRevision}}",
                "short": true
              }
              {{if .app.status.sync.revision}}
              ,
              {
                "title": "Commit",
                "value": "{{.app.spec.source.repoURL}}/{{.app.status.sync.revision}}",
                "short": true
              },{
                "title": "Author",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
                "short": true
              },{
                "title": "Message",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
                "short": true
              }
              {{end}}
              {{if .app.status.operationState.message}}
              ,
              {
                "title": "Error Message",
                "value": "{{.app.status.operationState.message}}",
                "short": true
              }
              {{end}}
              {{range $index, $c := .app.status.conditions}}
              {{if not $index}},{{end}}
              {{if $index}},{{end}}
              {
                "title": "{{$c.type}}",
                "value": "{{$c.message}}",
                "short": true
              }
              {{end}}
              ]
            }]
          }
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']