apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: "https://localhost:8889"     # TODO : url 환경마다 다름
  subscriptions: |
    - recipients:
      - webhook:slack-webhook
      triggers:
      - on-sync-succeeded
      - on-sync-status-unknown
  service.webhook.slack-webhook: |
    url: $slack-webhook-url
    headers:
      - name: Content-Type
        value: application/json
  template.app-sync-succeeded: |
    webhook:
      slack-webhook:
        method: POST
        body: |
          {
            "text": ":white_check_mark: {{.app.metadata.name}} has been successfully synced.",
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#18be52",
              "fields": [{
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              },{
                "title": "Path",
                "value": "{{.app.spec.source.path}}",
                "short": true
              },{
                "title": "Target Revision",
                "value": "{{.app.spec.source.targetRevision}}",
                "short": true
              },{
                "title": "Commit",
                "value": "{{.app.spec.source.repoURL}}/{{.app.status.sync.revision}}",
                "short": true
              },{
                "title": "Author",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
                "short": true
              },{
                "title": "Message",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
                "short": true
              },{
                "title": "Took",
                "value": "{{((call .time.Parse .app.status.operationState.finishedAt).Sub (call .time.Parse .app.status.operationState.startedAt)).Minutes}} min {{((call .time.Parse .app.status.operationState.finishedAt).Sub (call .time.Parse .app.status.operationState.startedAt)).Seconds}} sec",
                "short": true
              }]
            }]
          }
  template.app-sync-status-unknown: |
    webhook:
      slack-webhook:
        method: POST
        body: |
          {
            "text": ":exclamation: {{.app.metadata.name}} sync is 'Unknown'",
            "attachments": [{
              "title": "{{.app.metadata.name}}",
              "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
              "color": "#E96D76",
              "fields": [{
                "title": "Sync Status",
                "value": "{{.app.status.sync.status}}",
                "short": true
              },{
                "title": "Repository",
                "value": "{{.app.spec.source.repoURL}}",
                "short": true
              },{
                "title": "Path",
                "value": "{{.app.spec.source.path}}",
                "short": true
              },{
                "title": "Target Revision",
                "value": "{{.app.spec.source.targetRevision}}",
                "short": true
              },{
                "title": "Commit",
                "value": "{{.app.spec.source.repoURL}}/{{.app.status.sync.revision}}",
                "short": true
              },{
                "title": "Author",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
                "short": true
              },{
                "title": "Message",
                "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}",
                "short": true
              },{
                "title": "Took",
                "value": "{{((call .time.Parse .app.status.operationState.finishedAt).Sub (call .time.Parse .app.status.operationState.startedAt)).Minutes}} min {{((call .time.Parse .app.status.operationState.finishedAt).Sub (call .time.Parse .app.status.operationState.startedAt)).Seconds}} sec",
                "short": true
              }]
            }]
          }
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
