apiVersion: batch/v1
kind: Job
metadata:
  namespace: joo
  name: {{ .Chart.Name }}-{{ .Values.serviceName }}-post-sync
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "100"]