apiVersion: batch/v1
kind: Job
metadata:
  namespace: joo
  name: {{ .Chart.Name }}-{{ .Values.serviceName }}-pre-sync-1
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "100"]
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: joo
  name: {{ .Chart.Name }}-{{ .Values.serviceName }}-pre-sync-2
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "100"]